planning_task:
  description: |
    Generate a complete 32-week narrative plan for a member's journey with Elyx.

    **Primary Objective:** Your output must be a single, structured JSON object based on the `StoryPlan` Pydantic model.

    **Core Context:**
    You MUST ground your entire narrative plan in the following detailed context. This information is the single source of truth for this task.
    ---
    {hackathon_context}
    ---

    **Your Task:**
    1.  **Embody the Persona:** Create a story arc that deeply reflects the member's personality, goals, and challenges as described in the context.
    2.  **Integrate All Constraints:** Ensure every constraint from the context is woven into the 32-week plan, including scheduling the full diagnostic panels.
    3.  **Be Creative:** Create a compelling narrative with progress, realistic setbacks, and breakthroughs.
  expected_output: |
    A JSON object that strictly follows the `StoryPlan` Pydantic model, creating a creative and compelling 32-week narrative grounded in the provided context.